"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import Image from "next/image";
import { FileText, Eye, Download, CheckCircle2, X, ChevronLeft, ChevronRight } from "lucide-react";

/**
 * Sample Notes section — 2 cards (toggle by year).
 * View File opens a popup with CAROUSEL of PDF page images (not iframe).
 *
 * User spec:
 *   - "click korle popup hobe then carousel format a page gulo show korbe"
 *   - Sample PDFs hosted locally, converted to PNG page images
 *   - Year toggle: "1st year – view sample" / "2nd year – view sample"
 *   - Each year has 2 sub-cards: English + Bengali
 */

type SampleFile = {
  year: "1st" | "2nd";
  title: string;
  subtitle: string;
  englishUrl: string;
  bengaliUrl: string;
  englishPages: string[];
  bengaliPages: string[];
};

// Page image paths (statically known — generated by pdf-to-images.ts)
const PAGES_1ST_EN = Array.from({ length: 10 }, (_, i) => `/samples/pages/1st-year-english-${String(i + 1).padStart(2, "0")}.png`);
const PAGES_1ST_BN = Array.from({ length: 8 }, (_, i) => `/samples/pages/1st-year-bengali-${String(i + 1).padStart(2, "0")}.png`);
const PAGES_2ND_EN = Array.from({ length: 18 }, (_, i) => `/samples/pages/2nd-year-english-${String(i + 1).padStart(2, "0")}.png`);
const PAGES_2ND_BN = Array.from({ length: 13 }, (_, i) => `/samples/pages/2nd-year-bengali-${String(i + 1).padStart(2, "0")}.png`);

const SAMPLE_FILES: SampleFile[] = [
  {
    year: "1st",
    title: "1st Year Sample File",
    subtitle: "English + Bengali Translation — Pharmaceutics · Chapter 1",
    englishUrl: "/samples/1st-year-english-demo.pdf",
    bengaliUrl: "/samples/1st-year-bengali-demo.pdf",
    englishPages: PAGES_1ST_EN,
    bengaliPages: PAGES_1ST_BN,
  },
  {
    year: "2nd",
    title: "2nd Year Sample File",
    subtitle: "English + Bengali Translation — Pharmacology · Chapter 1",
    englishUrl: "/samples/2nd-year-english-demo.pdf",
    bengaliUrl: "/samples/2nd-year-bengali-demo.pdf",
    englishPages: PAGES_2ND_EN,
    bengaliPages: PAGES_2ND_BN,
  },
];

function CarouselModal({
  isOpen,
  onClose,
  pages,
  title,
  downloadUrl,
}: {
  isOpen: boolean;
  onClose: () => void;
  pages: string[];
  title: string;
  downloadUrl: string;
}) {
  const [current, setCurrent] = useState(0);
  const mountedRef = useRef(false);

  // Reset to first page when modal opens (mount or isOpen change)
  useEffect(() => {
    if (!mountedRef.current) {
      mountedRef.current = true;
      return;
    }
    if (isOpen) {
      const t = setTimeout(() => setCurrent(0), 0);
      return () => clearTimeout(t);
    }
  }, [isOpen]);

  // Lock body scroll
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [isOpen]);

  const goPrev = useCallback(() => {
    setCurrent((c) => (c === 0 ? pages.length - 1 : c - 1));
  }, [pages.length]);

  const goNext = useCallback(() => {
    setCurrent((c) => (c === pages.length - 1 ? 0 : c + 1));
  }, [pages.length]);

  // Keyboard navigation
  useEffect(() => {
    if (!isOpen) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === "ArrowLeft") goPrev();
      if (e.key === "ArrowRight") goNext();
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [isOpen, goPrev, goNext, onClose]);

  if (!isOpen || pages.length === 0) return null;

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 p-2 backdrop-blur-sm sm:p-4"
      onClick={onClose}
    >
      <div
        className="relative flex w-full max-w-3xl flex-col overflow-hidden rounded-2xl border border-border bg-card shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border bg-muted/40 px-4 py-3">
          <div className="flex items-center gap-3 min-w-0">
            <div className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-lg bg-primary/15 text-primary">
              <FileText className="h-5 w-5" />
            </div>
            <div className="min-w-0">
              <div className="truncate text-sm font-bold text-foreground">{title}</div>
              <div className="text-[11px] text-muted-foreground">
                Page {current + 1} of {pages.length}
              </div>
            </div>
          </div>
          <button
            onClick={onClose}
            className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full border border-border text-muted-foreground transition hover:bg-muted/50 hover:text-foreground"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Carousel */}
        <div className="relative flex h-[60vh] min-h-[400px] items-center justify-center bg-muted/20">
          {/* Prev button */}
          <button
            onClick={goPrev}
            className="absolute left-2 z-10 flex h-10 w-10 items-center justify-center rounded-full border border-border bg-card/90 text-foreground backdrop-blur transition hover:bg-muted"
            aria-label="Previous page"
          >
            <ChevronLeft className="h-5 w-5" />
          </button>

          {/* Current page */}
          <div className="relative h-full w-full">
            <Image
              src={pages[current]}
              alt={`Page ${current + 1}`}
              fill
              sizes="(max-width: 768px) 100vw, 768px"
              className="object-contain p-2"
              priority
            />
          </div>

          {/* Next button */}
          <button
            onClick={goNext}
            className="absolute right-2 z-10 flex h-10 w-10 items-center justify-center rounded-full border border-border bg-card/90 text-foreground backdrop-blur transition hover:bg-muted"
            aria-label="Next page"
          >
            <ChevronRight className="h-5 w-5" />
          </button>
        </div>

        {/* Thumbnails strip */}
        <div className="flex gap-2 overflow-x-auto border-t border-border bg-muted/30 p-3">
          {pages.map((page, i) => (
            <button
              key={i}
              onClick={() => setCurrent(i)}
              className={`relative h-16 w-12 flex-shrink-0 overflow-hidden rounded-md border-2 transition ${
                i === current
                  ? "border-primary ring-2 ring-primary/30"
                  : "border-border hover:border-primary/40"
              }`}
            >
              <Image
                src={page}
                alt={`Thumbnail ${i + 1}`}
                fill
                sizes="48px"
                className="object-cover"
              />
            </button>
          ))}
        </div>

        {/* Footer with download button */}
        <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border bg-muted/30 px-4 py-3">
          <span className="bn text-[11px] text-muted-foreground">
            স্যাম্পল ফাইল — সম্পূর্ণ নোটস কিনলে সব subject পাবেন
          </span>
          <a
            href={downloadUrl}
            download
            className="inline-flex items-center gap-1.5 rounded-full bg-primary px-4 py-2 text-xs font-bold text-primary-foreground transition hover:opacity-90"
          >
            <Download className="h-3.5 w-3.5" />
            ডাউনলোড করুন
          </a>
        </div>
      </div>
    </div>
  );
}

export function SampleNotes() {
  const [year, setYear] = useState<"1st" | "2nd">("1st");
  const [activeModal, setActiveModal] = useState<{
    title: string;
    pages: string[];
    downloadUrl: string;
  } | null>(null);

  const current = SAMPLE_FILES.find((f) => f.year === year) || SAMPLE_FILES[0];

  return (
    <section id="sample" className="relative py-16 sm:py-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        {/* Big, bold, colored heading */}
        <div className="text-center">
          <h2 className="text-3xl font-extrabold tracking-tight text-accent sm:text-4xl lg:text-5xl">
            Sample Notes
          </h2>
        </div>

        {/* year toggle */}
        <div className="mt-8 flex items-center justify-center gap-2">
          <button
            onClick={() => setYear("1st")}
            className={`rounded-full px-5 py-2 text-sm font-semibold transition ${
              year === "1st"
                ? "bg-primary text-primary-foreground shadow-lg shadow-primary/20"
                : "border border-border bg-card text-foreground hover:bg-muted/50"
            }`}
          >
            1st year – view sample
          </button>
          <button
            onClick={() => setYear("2nd")}
            className={`rounded-full px-5 py-2 text-sm font-semibold transition ${
              year === "2nd"
                ? "bg-primary text-primary-foreground shadow-lg shadow-primary/20"
                : "border border-border bg-card text-foreground hover:bg-muted/50"
            }`}
          >
            2nd year – view sample
          </button>
        </div>

        {/* Single sample file card (year-toggle based) */}
        <div className="mx-auto mt-8 max-w-4xl overflow-hidden rounded-2xl border border-border bg-card">
          <div className="grid gap-0 sm:grid-cols-5">
            {/* LEFT: Preview thumbnail */}
            <div className="relative min-h-[260px] overflow-hidden bg-gradient-to-br from-muted/50 to-card p-6 sm:col-span-2">
              <div className="pointer-events-none absolute inset-0 bg-grid opacity-30" />
              <div className="relative flex h-full flex-col items-center justify-center text-center">
                <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/15 ring-2 ring-primary/30">
                  <FileText className="h-8 w-8 text-primary" />
                </div>
                <div className="mt-4 text-xs font-semibold uppercase tracking-wider text-primary">
                  Sample Preview
                </div>
                <div className="mt-1 text-2xl font-bold text-foreground">
                  {year === "1st" ? "1st Year" : "2nd Year"}
                </div>
                <div className="bn mt-1 text-xs text-muted-foreground">
                  {year === "1st" ? "Pharmaceutics · Chapter 1" : "Pharmacology · Chapter 1"}
                </div>
                <div className="mt-4 flex flex-wrap justify-center gap-2 text-[10px]">
                  <span className="rounded-full bg-emerald-500/15 px-2 py-1 text-emerald-600 dark:text-emerald-400">PDF</span>
                  <span className="rounded-full bg-primary/15 px-2 py-1 text-primary">English</span>
                  <span className="rounded-full bg-accent/15 px-2 py-1 text-accent">বাংলা</span>
                </div>
              </div>
            </div>

            {/* RIGHT: Details + actions */}
            <div className="p-6 sm:col-span-3 sm:p-8">
              <h3 className="text-xl font-bold text-foreground sm:text-2xl">
                {current.title}
              </h3>
              <p className="bn mt-2 text-sm leading-relaxed text-muted-foreground">
                এই স্যাম্পলে আপনি দেখবেন: chapter summary, VVI MCQ/SAQ/FIB, সহজ ভাষায়
                explanation, বাংলা translation এবং পরীক্ষা-ভিত্তিক সাজেশন।
              </p>

              <ul className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2">
                {[
                  "Chapter Summary",
                  "VVI MCQ + SAQ",
                  "Bengali Translation",
                  "Long Question-Answer",
                ].map((t) => (
                  <li key={t} className="flex items-center gap-2 text-xs text-foreground/80">
                    <CheckCircle2 className="h-3.5 w-3.5 flex-shrink-0 text-emerald-500" />
                    <span className="bn">{t}</span>
                  </li>
                ))}
              </ul>

              {/* Two cards: English version + Bengali version */}
              <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2">
                <div className="rounded-xl border border-border bg-muted/30 p-4">
                  <div className="flex items-center gap-2">
                    <span className="rounded-full bg-primary/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-primary">
                      English
                    </span>
                  </div>
                  <h4 className="bn mt-2 text-[12px] font-semibold text-foreground">
                    English Version Sample
                  </h4>
                  <div className="mt-3 flex gap-2">
                    <button
                      onClick={() =>
                        setActiveModal({
                          title: `${current.title} — English Version`,
                          pages: current.englishPages,
                          downloadUrl: current.englishUrl,
                        })
                      }
                      className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-full bg-primary px-3 py-1.5 text-[11px] font-bold text-primary-foreground transition hover:opacity-90"
                    >
                      <Eye className="h-3 w-3" />
                      View File
                    </button>
                    <a
                      href={current.englishUrl}
                      download
                      className="inline-flex items-center justify-center gap-1.5 rounded-full border border-border bg-card px-3 py-1.5 text-[11px] font-semibold text-foreground transition hover:bg-muted/50"
                    >
                      <Download className="h-3 w-3" />
                    </a>
                  </div>
                </div>

                <div className="rounded-xl border border-border bg-muted/30 p-4">
                  <div className="flex items-center gap-2">
                    <span className="rounded-full bg-accent/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-accent">
                      বাংলা
                    </span>
                  </div>
                  <h4 className="bn mt-2 text-[12px] font-semibold text-foreground">
                    Bengali Translation Sample
                  </h4>
                  <div className="mt-3 flex gap-2">
                    <button
                      onClick={() =>
                        setActiveModal({
                          title: `${current.title} — Bengali Version`,
                          pages: current.bengaliPages,
                          downloadUrl: current.bengaliUrl,
                        })
                      }
                      className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-full bg-accent px-3 py-1.5 text-[11px] font-bold text-accent-foreground transition hover:opacity-90"
                    >
                      <Eye className="h-3 w-3" />
                      View File
                    </button>
                    <a
                      href={current.bengaliUrl}
                      download
                      className="inline-flex items-center justify-center gap-1.5 rounded-full border border-border bg-card px-3 py-1.5 text-[11px] font-semibold text-foreground transition hover:bg-muted/50"
                    >
                      <Download className="h-3 w-3" />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Carousel modal */}
      <CarouselModal
        isOpen={activeModal !== null}
        onClose={() => setActiveModal(null)}
        pages={activeModal?.pages || []}
        title={activeModal?.title || ""}
        downloadUrl={activeModal?.downloadUrl || ""}
      />
    </section>
  );
}
